# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stats.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstats.proto\x12\x03\x61pi\"\x1b\n\tSearchReq\x12\x0e\n\x06search\x18\x01 \x01(\t\"7\n\x0cGetStatsResp\x12\'\n\rstatsEntities\x18\x01 \x03(\x0b\x32\x10.api.StatsEntity\"b\n\x0bStatsEntity\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x10\n\x08Username\x18\x02 \x01(\t\x12\x11\n\tFirstName\x18\x03 \x01(\t\x12\x10\n\x08LastName\x18\x04 \x01(\t\x12\x10\n\x08\x43ockSize\x18\x05 \x01(\x05\x32\x33\n\x05Stats\x12*\n\x03Get\x12\x0e.api.SearchReq\x1a\x11.api.GetStatsResp\"\x00\x42\x07Z\x05./apib\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stats_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\005./api'
  _SEARCHREQ._serialized_start=20
  _SEARCHREQ._serialized_end=47
  _GETSTATSRESP._serialized_start=49
  _GETSTATSRESP._serialized_end=104
  _STATSENTITY._serialized_start=106
  _STATSENTITY._serialized_end=204
  _STATS._serialized_start=206
  _STATS._serialized_end=257
# @@protoc_insertion_point(module_scope)
